-- Migration: 006 - Create current order draft table
CREATE TABLE IF NOT EXISTS order_drafts (
    id TINYINT UNSIGNED NOT NULL,
    order_type VARCHAR(20) NOT NULL DEFAULT 'dineIn',
    tax_rate INT UNSIGNED NOT NULL DEFAULT 10,
    subtotal INT UNSIGNED NOT NULL DEFAULT 0,
    tax_total INT UNSIGNED NOT NULL DEFAULT 0,
    total INT UNSIGNED NOT NULL DEFAULT 0,
    items_json JSON NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
